name: {{ action_name.snakeCase() }}
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Using this fork of the actions-toolkit-dart package as the output control
  # is using the deprecated commands in the main package.
  # You can change this back to the main package if your action doesn't have any outputs.
  actions_toolkit_dart:
    git:
      url: https://github.com/abitofevrything/actions-toolkit-dart
      ref: feat/environment-state-output
