name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        uses: abitofevrything/publish-mason-brick@1.0.3
        with:
          email: ${{ secrets.BRICKHUB_EMAIL }}
          password: ${{ secrets.BRICKHUB_PASSWORD }}
